In [1]:
from dask.array import multiply
from sklearn.externals.array_api_compat.dask.array import ones_like
%load_ext cudf.pandas

# <center>**<u>An Introduction to TensorFlow</u>**</center>

---


In [25]:
# BASIC IMPORTS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import tensorflow as tf
from tensorflow import constant, add, multiply, matmul, ones_like, ones, Variable, zeros,  zeros_like, fill



# GPU OPTIMIZATIONS
import cudf

## **TensorFlow Basics: Defining Tensors, Constants, and Variables**

---


### <u>Defining Tensors</u>

- Tensors are multi-dimensional arrays that can hold numerical data. They are the fundamental data structure in TensorFlow and are used to represent inputs, outputs, and intermediate values in machine learning models.

In [14]:
# 0D Tensor
d0 = tf.ones((1,))

# 1D Tensor
d1 = tf.ones((2,))

#2D Tensor
d2 = tf.ones((2,2))

#3D Tensor
d3 = tf.ones((2, 2, 2))


# Print
print(f"d0={d0.numpy()}\nd1={d1.numpy()}\nd2={d2.numpy()}\nd3={d3.numpy()}")

d0=[1.]
d1=[1. 1.]
d2=[[1. 1.]
 [1. 1.]]
d3=[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### <u>Defining Constants</u>

- Constants are immutable values that cannot be changed during the execution of a program. They are useful for representing fixed values that should not be altered, such as mathematical constants like pi or physical constants like the speed of light.

In [16]:
# 2x3 constant
a = constant(3, shape=[2, 3])

# 2x2 constant
b = constant([1, 2, 3, 4], shape=[2, 2])

print(a, b)

tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#### Constants Convience Functions

|                                        Operation                                         |                                  Description                                  |
|:----------------------------------------------------------------------------------------:|:-----------------------------------------------------------------------------:|
|                `tensorflow.zeros(shape, dtype=tf.float32, name='zeros')`                 |                Creates a tensor with all elements set to zero.                |
|                  `tensorflow.zeros_like(input, dtype=None, name=None)`                   |  Creates a tensor of zeros with the same shape and type as the input tensor.  |
|                 `tensorflow.ones(shape, dtype=tf.float32, name='ones')`                  |                Creates a tensor with all elements set to one.                 |
|                   `tensorflow.ones_like(input, dtype=None, name=None)`                   |  Creates a tensor of ones with the same shape and type as the input tensor.   |
|                       `tensorflow.fill(dims, value, name='fill')`                        | Creates a tensor with the given shape and fills it with the specified value.  |

### <u>Definig Variables</u>
- Variables are

In [17]:
# define variables
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
b0 = tf.Variable([6, 5, 4, 3, 2, 1], dtype=tf.float32)

# define a constant to use
c = tf.constant(3, tf.float32)

# compute the product of each variable and the constant
a0c = tf.multiply(a0, c)
b0c = b0*c

print(a0c, b0c)

tf.Tensor([ 3.  6.  9. 12. 15. 18.], shape=(6,), dtype=float32) tf.Tensor([18. 15. 12.  9.  6.  3.], shape=(6,), dtype=float32)


## **Basic Operations in TensorFlow**

---
- <u>element-wise multiplication</u>
    - Performs element-wise multiplication between two tensors of the same shape
- <u>matrix multiplication</u>
    - Performs matrix multiplication between two tensors

---
- some basic TensorFlow operations:
    - `add()`:
    - `multiply()`:
    - `matmul()`:
    - `reduce_sum()`:

---
### EXERCISE
- define tensors `A1` and `A23`
- set `B1` to be a tensor with the same shape as `A1`
- set `B23` to be a tensor with the same shape as `A23`
- set `C1` and `C23`equal to the element-wise products of `A1` and `B1`, and `A23` and `B23`respectively

In [24]:
# Define tensors A1 and A23 as constants
A1 = tf.constant([1, 2, 3, 4])
A23 = tf.constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = tf.ones_like([2, 5, 3, 2])
B23 = tf.ones_like([2, 5, 6])

# Perform element-wise multiplication
C1 = tf.multiply(A1, B1)
C23 = tf.multiply(A23, B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))


 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


## **Advanced Operations in TensorFlow**

---
| Operation | Use|
| :---------: | :--------: |
| `.gradient()` | Computes the clope of a function at a point |
| `.reshape()` | Reshapes a tensor (i.e. `10x10` to `100x1`) |
| `.random()` | Populates tensor with entries drawn from a probability distribution |

---

### EXERCISE
-

## **Importing and Converting Data with TensorFlow**

---


### EXERCISE

## **Loss Functions**

---


## **Linear Regression**

---

##  **Batch Training**

---